// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: knobCircle

#include "../ui.h"

void ui_blackScreen_screen_init(void)
{
ui_blackScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_blackScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_blackScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_blackScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_blackScreen, ui_event_blackScreen, LV_EVENT_ALL, NULL);

}
