// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: knobCircle

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 150);
    lv_obj_set_height(ui_Button3, 150);
    lv_obj_set_x(ui_Button3, 80);
    lv_obj_set_y(ui_Button3, 70);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Button3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button3, 100, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_bulb_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 150);
    lv_obj_set_height(ui_Button1, 150);
    lv_obj_set_x(ui_Button1, -80);
    lv_obj_set_y(ui_Button1, 70);
    lv_obj_set_align(ui_Button1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button1, 100, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_bulb_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 150);
    lv_obj_set_height(ui_Button2, 150);
    lv_obj_set_x(ui_Button2, 80);
    lv_obj_set_y(ui_Button2, -70);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Button2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button2, 100, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Button2, &ui_img_curtain_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 150);
    lv_obj_set_height(ui_Button4, 150);
    lv_obj_set_x(ui_Button4, -80);
    lv_obj_set_y(ui_Button4, -70);
    lv_obj_set_align(ui_Button4, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Button4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x3399FF), LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button4, 100, LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_2047347433, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resetWifi = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_resetWifi, 50);
    lv_obj_set_height(ui_resetWifi, 50);
    lv_obj_set_x(ui_resetWifi, 0);
    lv_obj_set_y(ui_resetWifi, 200);
    lv_obj_set_align(ui_resetWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_resetWifi, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_resetWifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_resetWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resetWifi, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_resetWifi, &ui_img_1968931049, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_resetWifi, lv_color_hex(0x3399FF), LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_resetWifi, 100, LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_resetWifi, ui_event_resetWifi, LV_EVENT_ALL, NULL);

}
