// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: knobCircle

#ifndef _KNOBCIRCLE_UI_H
#define _KNOBCIRCLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_resetWifi;
void ui_event_resetWifi(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_lumi_png);    // assets\lumi.png
LV_IMG_DECLARE(ui_img_bulb_png);    // assets\bulb.png
LV_IMG_DECLARE(ui_img_curtain_png);    // assets\curtain.png
LV_IMG_DECLARE(ui_img_2047347433);    // assets\air-conditioner.png
LV_IMG_DECLARE(ui_img_1968931049);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
